---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build for Linux
  image: rust:alpine
  environment:
    RUSTFLAGS: -D warnings
  commands:
    - apk add --no-cache musl-dev
    - rustup install nightly
    - cargo +nightly update
    - cargo +nightly check --release
    - cargo +nightly build --release
    - cp -p target/release/galry target/release/galry.tmp
    - mv -f target/release/galry.tmp target/release/galry

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/galry
    tags: latest-amd64
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/galry:latest-amd64"
  when:
    event:
      exclude:
      - pull_request

---
kind: pipeline
name: linux-armv7l

platform:
  os: linux
  arch: arm

steps:
- name: build for Linux
  image: rust:latest
  environment:
    RUSTFLAGS: -D warnings
  commands:
    - rustup install nightly
    - cargo +nightly update
    - cargo +nightly build --release
    - cp -p target/release/galry target/release/galry.tmp
    - mv -f target/release/galry.tmp target/release/galry

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/galry
    tags: latest-armv7l
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/galry:latest-armv7l"
  when:
    event:
      exclude:
      - pull_request

depends_on:
- linux-amd64


---
kind: pipeline
type: docker
name: manifest

steps:
- name: publish
  image: plugins/manifest:1.2
  settings:
    ignore_missing: true
    spec: docker-manifest.tmpl
    username: svedrin
    password:
      from_secret: docker-registry-pw

trigger:
  event:
    exclude:
    - pull_request

depends_on:
- linux-amd64
- linux-armv7l


---
kind: signature
hmac: 5d4882043676ba612c0a44338e62a145a7198bcf38575c481fb8bf5635d965c6

...
