---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build for Linux
  image: rust:alpine
  environment:
    RUSTFLAGS: -D warnings
  commands:
    - apk add --no-cache musl-dev
    - rustup install nightly
    - cargo +nightly check --release
    - cargo +nightly build --release
    - cp -p target/release/galry target/release/galry.tmp
    - mv -f target/release/galry.tmp target/release/galry

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/galry
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/galry:latest"
  when:
    event:
      exclude:
      - pull_request

---
kind: pipeline
name: linux-arm

platform:
  os: linux
  arch: arm

steps:
- name: build for Linux
  image: rust:latest
  environment:
    RUSTFLAGS: -D warnings
  commands:
    - rustup install nightly
    - cargo +nightly check --release
    - cargo +nightly build --release
    - cp -p target/release/galry target/release/galry.tmp
    - mv -f target/release/galry.tmp target/release/galry

- name: build docker image
  image: plugins/docker
  settings:
    repo: svedrin/galry
    username: svedrin
    password:
      from_secret: docker-registry-pw
    cache_from: "svedrin/galry:latest-armv7l"
  when:
    event:
      exclude:
      - pull_request

depends_on:
- linux-amd64

---
kind: signature
hmac: 91599ad6a628f86a028f416c276ea593f974cfbd556eac13e511819c59b5cc5e

...
