[package]
name = "galry"
version = "0.1.0"
authors = ["Michael Ziegler <ich@michaelziegler.name>"]
edition = "2018"

[dependencies]
clap = "*"
image = "0.23.2"
kamadak-exif = "0.5.1"
lazy_static = "1.0"
rocket = "0.4.5"
structopt = "0.3"
tera = "1.0"
